# Generated by Django 5.2 on 2025-04-21 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSentimentScoreHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_intensity_score', models.FloatField()),
                ('average_ordinal_sentiment', models.CharField(max_length=20)),
                ('personal_sentiment_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
