# Generated by Django 5.2 on 2025-04-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_usersentimentscorehistory_personal_sentiment_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersentimentscorehistory',
            name='personal_sentiment_score',
            field=models.FloatField(),
        ),
    ]
