# Generated by Django 5.1.6 on 2025-03-20 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_loan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Loan',
        ),
    ]
