# Generated by Django 5.1.6 on 2025-04-25 07:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditScoreHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(help_text='Credit score (300-850)')),
                ('calculation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('income', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('age', models.PositiveIntegerField(null=True)),
                ('employment_length', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('debt_to_income', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('credit_utilization', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('payment_history', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('credit_mix', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('new_credit', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('credit_history_length', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('public_records', models.PositiveIntegerField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-calculation_date'],
            },
        ),
        migrations.CreateModel(
            name='LoanAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(choices=[('personal', 'Personal Loan'), ('mortgage', 'Mortgage'), ('auto', 'Auto Loan'), ('student', 'Student Loan'), ('credit_card', 'Credit Card'), ('other', 'Other')], max_length=20)),
                ('lender', models.CharField(max_length=100)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('term_months', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('monthly_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remaining_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserFinancialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly income in Kenyan Shillings', max_digits=12, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('employment_length', models.DecimalField(blank=True, decimal_places=2, help_text='Years of employment', max_digits=5, null=True)),
                ('debt_to_income', models.DecimalField(blank=True, decimal_places=2, help_text='Debt-to-income ratio (0.0-1.0)', max_digits=5, null=True)),
                ('credit_utilization', models.DecimalField(blank=True, decimal_places=2, help_text='Credit utilization ratio (0.0-1.0)', max_digits=5, null=True)),
                ('payment_history', models.DecimalField(blank=True, decimal_places=2, help_text='Payment history score (0.0-1.0)', max_digits=5, null=True)),
                ('credit_mix', models.DecimalField(blank=True, decimal_places=2, help_text='Credit mix score (0.0-1.0)', max_digits=5, null=True)),
                ('new_credit', models.DecimalField(blank=True, decimal_places=2, help_text='New credit score (0.0-1.0)', max_digits=5, null=True)),
                ('credit_history_length', models.DecimalField(blank=True, decimal_places=2, help_text='Length of credit history in years', max_digits=5, null=True)),
                ('public_records', models.PositiveIntegerField(default=0, help_text='Number of public records')),
                ('loan_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Total loan amount', max_digits=12, null=True)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Average interest rate', max_digits=5, null=True)),
                ('monthly_payment', models.DecimalField(blank=True, decimal_places=2, help_text='Total monthly payment', max_digits=10, null=True)),
                ('total_accounts', models.PositiveIntegerField(default=0, help_text='Total number of accounts')),
                ('delinquent_accounts', models.PositiveIntegerField(default=0, help_text='Number of delinquent accounts')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
