# Generated by Django 5.1.6 on 2025-05-01 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfinancialprofile',
            name='current_credit_balance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Current total balance on all credit accounts', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='userfinancialprofile',
            name='monthly_debt_payment',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total monthly debt payments', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='userfinancialprofile',
            name='total_credit_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total credit limit across all accounts', max_digits=12, null=True),
        ),
    ]
