# Generated by Django 5.1.6 on 2025-05-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_userfinancialprofile_current_credit_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditscorehistory',
            name='current_credit_balance',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='creditscorehistory',
            name='monthly_debt_payment',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='creditscorehistory',
            name='total_credit_limit',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
